# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en
  contentDir: content/en
  params:
    description: Site description in English...
  title: Physics Department SAMPS NTUA
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  # contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
el:
  languageCode: el
  contentDir: content/el
  title: Εργαστήριο Βιοφωτονικής
  params:
    description: Site description in Greek...
