# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Tour
    url: /el/tour
    weight: 10
  - name: Νέα
    url: /el/post
    weight: 20
  - name: Προσωπικό
    url: /el/people
    weight: 30
  # - name: Events
  #   url: event
  #   weight: 40
  - name: Δημοσιεύσεις
    url: /el/publication
    weight: 50
  - name: Διπλωματικές
    url: /el/project
    weight: 55
  - name: Επικοινωνία
    url: /el/contact
    weight: 60
