# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About us
    pageref: /about-us
    weight: 10
  - name: News
    pageref: post
    weight: 20
  - name: People
    pageref: people
    weight: 30
  # - name: Events
  #   url: event
  #   weight: 40
  - name: Research
    # pageref: research
    weight: 40
  - name: Publications
    parent: Research
    pageref: publication
    weight: 41

  - name: Projects
    parent: Research
    pageref: project
    weight: 42

  - name: Teaching
    identifier: teaching
    weight: 50

  - name: Courses
    parent: teaching
    pageref: courses
    weight: 51
  
  - name: Available thesis projects
    parent: teaching
    pageref: thesis-projects
    weight: 52

  - name: Diploma Theses
    identifier: diploma-theses
    parent: teaching
    pageRef: /theses/diploma
    weight: 53
  
  - name: Talks
    pageref: talks
    weight: 70
  - name: Contact
    pageref: contact
    weight: 80
