# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About us
    pageref: /about-us
    weight: 10
  - name: Νέα
    pageref: post
    weight: 20
  - name: Προσωπικό
    pageref: people
    weight: 30
  # - name: Events
  #   url: event
  #   weight: 40
  - name: Έρευνα
    identifier: research
    # pageref: research
    weight: 40
  - name: Δημοσιεύσεις
    parent: research
    pageref: publication
    weight: 41
  - name: Projects
    parent: research
    pageref: project
    weight: 42
  - name: Διδασκαλία
    identifier: teaching
    pageref: teaching
    weight: 50
  - name: Μαθήματα
    parent: teaching
    pageref: courses
    weight: 51
  
  - name: Προτεινόμενες διπλωματικές
    parent: teaching
    pageref: thesis-projects
    weight: 52

  - name: Διπλωματικές εργασίες
    identifier: theses
    parent: teaching
    pageRef: /theses/diploma/
    weight: 60
  
  - name: Talks
    pageref: talks
    weight: 70
  - name: Contact
    pageref: contact
    weight: 80
